# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 500))
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.stackedWidget.setMinimumSize(QtCore.QSize(700, 500))
        self.stackedWidget.setMaximumSize(QtCore.QSize(700, 500))
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.entry_btn = QtWidgets.QPushButton(self.main_page)
        self.entry_btn.setGeometry(QtCore.QRect(255, 262, 200, 30))
        self.entry_btn.setMinimumSize(QtCore.QSize(200, 30))
        self.entry_btn.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.entry_btn.setFont(font)
        self.entry_btn.setStyleSheet("background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;")
        self.entry_btn.setObjectName("entry_btn")
        self.regisration_btn = QtWidgets.QPushButton(self.main_page)
        self.regisration_btn.setGeometry(QtCore.QRect(255, 312, 200, 30))
        self.regisration_btn.setMinimumSize(QtCore.QSize(200, 30))
        self.regisration_btn.setMaximumSize(QtCore.QSize(200, 30))
        self.regisration_btn.setStyleSheet("\n"
"box-sizing: border-box;\n"
"\n"
"position: absolute;\n"
"width: 200px;\n"
"height: 30px;\n"
"left: 255px;\n"
"top: 262px;\n"
"\n"
"background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;")
        self.regisration_btn.setObjectName("regisration_btn")
        self.label_9 = QtWidgets.QLabel(self.main_page)
        self.label_9.setGeometry(QtCore.QRect(123, 157, 453, 35))
        self.label_9.setMinimumSize(QtCore.QSize(453, 35))
        self.label_9.setMaximumSize(QtCore.QSize(453, 35))
        self.label_9.setStyleSheet("\n"
"\n"
"\n"
"\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 145%;")
        self.label_9.setObjectName("label_9")
        self.regisration_btn.raise_()
        self.entry_btn.raise_()
        self.label_9.raise_()
        self.stackedWidget.addWidget(self.main_page)
        self.table_page_rooms = QtWidgets.QWidget()
        self.table_page_rooms.setObjectName("table_page_rooms")
        self.table_of_rooms = QtWidgets.QTableWidget(self.table_page_rooms)
        self.table_of_rooms.setGeometry(QtCore.QRect(30, 60, 641, 341))
        self.table_of_rooms.setStyleSheet("")
        self.table_of_rooms.setObjectName("table_of_rooms")
        self.table_of_rooms.setColumnCount(6)
        self.table_of_rooms.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rooms.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rooms.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rooms.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rooms.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rooms.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_rooms.setHorizontalHeaderItem(5, item)
        self.back_btn_rooms = QtWidgets.QPushButton(self.table_page_rooms)
        self.back_btn_rooms.setGeometry(QtCore.QRect(40, 30, 56, 17))
        self.back_btn_rooms.setObjectName("back_btn_rooms")
        self.label_16 = QtWidgets.QLabel(self.table_page_rooms)
        self.label_16.setGeometry(QtCore.QRect(230, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.search_input_rooms = QtWidgets.QLineEdit(self.table_page_rooms)
        self.search_input_rooms.setGeometry(QtCore.QRect(420, 20, 171, 21))
        self.search_input_rooms.setObjectName("search_input_rooms")
        self.search_btn_rooms = QtWidgets.QPushButton(self.table_page_rooms)
        self.search_btn_rooms.setGeometry(QtCore.QRect(70, 430, 91, 31))
        self.search_btn_rooms.setObjectName("search_btn_rooms")
        self.delete_btn_rooms = QtWidgets.QPushButton(self.table_page_rooms)
        self.delete_btn_rooms.setGeometry(QtCore.QRect(200, 430, 91, 31))
        self.delete_btn_rooms.setObjectName("delete_btn_rooms")
        self.edit_btn_rooms = QtWidgets.QPushButton(self.table_page_rooms)
        self.edit_btn_rooms.setGeometry(QtCore.QRect(350, 430, 91, 31))
        self.edit_btn_rooms.setObjectName("edit_btn_rooms")
        self.sorting_btn_rooms = QtWidgets.QPushButton(self.table_page_rooms)
        self.sorting_btn_rooms.setGeometry(QtCore.QRect(480, 430, 91, 31))
        self.sorting_btn_rooms.setObjectName("sorting_btn_rooms")
        self.stackedWidget.addWidget(self.table_page_rooms)
        self.table_page_proc = QtWidgets.QWidget()
        self.table_page_proc.setObjectName("table_page_proc")
        self.table_of_proc = QtWidgets.QTableWidget(self.table_page_proc)
        self.table_of_proc.setGeometry(QtCore.QRect(30, 70, 641, 341))
        self.table_of_proc.setStyleSheet("")
        self.table_of_proc.setObjectName("table_of_proc")
        self.table_of_proc.setColumnCount(6)
        self.table_of_proc.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_proc.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_proc.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_proc.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_proc.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_proc.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_proc.setHorizontalHeaderItem(5, item)
        self.back_btn_proc = QtWidgets.QPushButton(self.table_page_proc)
        self.back_btn_proc.setGeometry(QtCore.QRect(40, 20, 56, 17))
        self.back_btn_proc.setObjectName("back_btn_proc")
        self.label_15 = QtWidgets.QLabel(self.table_page_proc)
        self.label_15.setGeometry(QtCore.QRect(260, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.search_input_proc = QtWidgets.QLineEdit(self.table_page_proc)
        self.search_input_proc.setGeometry(QtCore.QRect(480, 20, 171, 21))
        self.search_input_proc.setObjectName("search_input_proc")
        self.search_btn_proc = QtWidgets.QPushButton(self.table_page_proc)
        self.search_btn_proc.setGeometry(QtCore.QRect(70, 430, 91, 31))
        self.search_btn_proc.setObjectName("search_btn_proc")
        self.delete_btn_proc = QtWidgets.QPushButton(self.table_page_proc)
        self.delete_btn_proc.setGeometry(QtCore.QRect(190, 430, 91, 31))
        self.delete_btn_proc.setObjectName("delete_btn_proc")
        self.edit_btn_proc = QtWidgets.QPushButton(self.table_page_proc)
        self.edit_btn_proc.setGeometry(QtCore.QRect(330, 430, 91, 31))
        self.edit_btn_proc.setObjectName("edit_btn_proc")
        self.sorting_btn_proc = QtWidgets.QPushButton(self.table_page_proc)
        self.sorting_btn_proc.setGeometry(QtCore.QRect(470, 430, 91, 31))
        self.sorting_btn_proc.setObjectName("sorting_btn_proc")
        self.stackedWidget.addWidget(self.table_page_proc)
        self.table_page_clients = QtWidgets.QWidget()
        self.table_page_clients.setObjectName("table_page_clients")
        self.table_of_clients = QtWidgets.QTableWidget(self.table_page_clients)
        self.table_of_clients.setGeometry(QtCore.QRect(30, 80, 641, 341))
        self.table_of_clients.setStyleSheet("")
        self.table_of_clients.setObjectName("table_of_clients")
        self.table_of_clients.setColumnCount(6)
        self.table_of_clients.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_clients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_clients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_clients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_clients.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_clients.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_clients.setHorizontalHeaderItem(5, item)
        self.label_14 = QtWidgets.QLabel(self.table_page_clients)
        self.label_14.setGeometry(QtCore.QRect(280, 30, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.back_btn_clients = QtWidgets.QPushButton(self.table_page_clients)
        self.back_btn_clients.setGeometry(QtCore.QRect(40, 30, 56, 17))
        self.back_btn_clients.setObjectName("back_btn_clients")
        self.search_btn_clients = QtWidgets.QPushButton(self.table_page_clients)
        self.search_btn_clients.setGeometry(QtCore.QRect(60, 430, 91, 31))
        self.search_btn_clients.setObjectName("search_btn_clients")
        self.delete_btn_clients = QtWidgets.QPushButton(self.table_page_clients)
        self.delete_btn_clients.setGeometry(QtCore.QRect(190, 430, 91, 31))
        self.delete_btn_clients.setObjectName("delete_btn_clients")
        self.edit_btn_clients = QtWidgets.QPushButton(self.table_page_clients)
        self.edit_btn_clients.setGeometry(QtCore.QRect(320, 430, 91, 31))
        self.edit_btn_clients.setObjectName("edit_btn_clients")
        self.sorting_btn_clients = QtWidgets.QPushButton(self.table_page_clients)
        self.sorting_btn_clients.setGeometry(QtCore.QRect(460, 430, 91, 31))
        self.sorting_btn_clients.setObjectName("sorting_btn_clients")
        self.search_input_clients = QtWidgets.QLineEdit(self.table_page_clients)
        self.search_input_clients.setGeometry(QtCore.QRect(510, 30, 171, 21))
        self.search_input_clients.setObjectName("search_input_clients")
        self.stackedWidget.addWidget(self.table_page_clients)
        self.table_page_empl = QtWidgets.QWidget()
        self.table_page_empl.setObjectName("table_page_empl")
        self.table_of_emlp = QtWidgets.QTableWidget(self.table_page_empl)
        self.table_of_emlp.setGeometry(QtCore.QRect(35, 61, 641, 341))
        self.table_of_emlp.setStyleSheet("")
        self.table_of_emlp.setObjectName("table_of_emlp")
        self.table_of_emlp.setColumnCount(8)
        self.table_of_emlp.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_emlp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_emlp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_emlp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_emlp.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_emlp.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_emlp.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_emlp.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_of_emlp.setHorizontalHeaderItem(7, item)
        self.back_btn_empl = QtWidgets.QPushButton(self.table_page_empl)
        self.back_btn_empl.setGeometry(QtCore.QRect(20, 20, 56, 17))
        self.back_btn_empl.setObjectName("back_btn_empl")
        self.sorting_btn_empl = QtWidgets.QPushButton(self.table_page_empl)
        self.sorting_btn_empl.setGeometry(QtCore.QRect(490, 420, 91, 31))
        self.sorting_btn_empl.setObjectName("sorting_btn_empl")
        self.delete_btn_empl = QtWidgets.QPushButton(self.table_page_empl)
        self.delete_btn_empl.setGeometry(QtCore.QRect(220, 420, 91, 31))
        self.delete_btn_empl.setObjectName("delete_btn_empl")
        self.edit_btn_empl = QtWidgets.QPushButton(self.table_page_empl)
        self.edit_btn_empl.setGeometry(QtCore.QRect(350, 420, 91, 31))
        self.edit_btn_empl.setObjectName("edit_btn_empl")
        self.label_8 = QtWidgets.QLabel(self.table_page_empl)
        self.label_8.setGeometry(QtCore.QRect(210, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.search_input_empl = QtWidgets.QLineEdit(self.table_page_empl)
        self.search_input_empl.setGeometry(QtCore.QRect(510, 20, 171, 21))
        self.search_input_empl.setObjectName("search_input_empl")
        self.search_btn_empl = QtWidgets.QPushButton(self.table_page_empl)
        self.search_btn_empl.setGeometry(QtCore.QRect(80, 420, 91, 31))
        self.search_btn_empl.setObjectName("search_btn_empl")
        self.stackedWidget.addWidget(self.table_page_empl)
        self.registration_page = QtWidgets.QWidget()
        self.registration_page.setObjectName("registration_page")
        self.label_4 = QtWidgets.QLabel(self.registration_page)
        self.label_4.setGeometry(QtCore.QRect(265, 123, 169, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 145%;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.reg_btn_reg_page = QtWidgets.QPushButton(self.registration_page)
        self.reg_btn_reg_page.setGeometry(QtCore.QRect(255, 348, 200, 30))
        self.reg_btn_reg_page.setMinimumSize(QtCore.QSize(200, 30))
        self.reg_btn_reg_page.setMaximumSize(QtCore.QSize(200, 30))
        self.reg_btn_reg_page.setStyleSheet("background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;\n"
"color: #FFFFFF;")
        self.reg_btn_reg_page.setObjectName("reg_btn_reg_page")
        self.reg_login_edit = QtWidgets.QLineEdit(self.registration_page)
        self.reg_login_edit.setGeometry(QtCore.QRect(255, 198, 200, 30))
        self.reg_login_edit.setMinimumSize(QtCore.QSize(200, 30))
        self.reg_login_edit.setMaximumSize(QtCore.QSize(200, 30))
        self.reg_login_edit.setStyleSheet("border: 1px solid #006F48;\n"
"border-radius: 10px;")
        self.reg_login_edit.setObjectName("reg_login_edit")
        self.reg_pass_edit = QtWidgets.QLineEdit(self.registration_page)
        self.reg_pass_edit.setGeometry(QtCore.QRect(255, 248, 200, 30))
        self.reg_pass_edit.setMinimumSize(QtCore.QSize(200, 30))
        self.reg_pass_edit.setMaximumSize(QtCore.QSize(200, 30))
        self.reg_pass_edit.setStyleSheet("border: 1px solid #006F48;\n"
"border-radius: 10px;")
        self.reg_pass_edit.setObjectName("reg_pass_edit")
        self.reg_pass_edit_2 = QtWidgets.QLineEdit(self.registration_page)
        self.reg_pass_edit_2.setGeometry(QtCore.QRect(255, 298, 200, 30))
        self.reg_pass_edit_2.setMinimumSize(QtCore.QSize(200, 30))
        self.reg_pass_edit_2.setMaximumSize(QtCore.QSize(200, 30))
        self.reg_pass_edit_2.setStyleSheet("border: 1px solid #006F48;\n"
"border-radius: 10px;")
        self.reg_pass_edit_2.setObjectName("reg_pass_edit_2")
        self.back_btn_reg = QtWidgets.QPushButton(self.registration_page)
        self.back_btn_reg.setGeometry(QtCore.QRect(30, 30, 25, 25))
        self.back_btn_reg.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_reg.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_btn_reg.setFont(font)
        self.back_btn_reg.setStyleSheet("border-radius: 10px;\n"
"")
        self.back_btn_reg.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-стрелка-влево-в-круге-2-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn_reg.setIcon(icon)
        self.back_btn_reg.setIconSize(QtCore.QSize(25, 25))
        self.back_btn_reg.setObjectName("back_btn_reg")
        self.stackedWidget.addWidget(self.registration_page)
        self.entry_page = QtWidgets.QWidget()
        self.entry_page.setObjectName("entry_page")
        self.entry_btn_entry_page = QtWidgets.QPushButton(self.entry_page)
        self.entry_btn_entry_page.setGeometry(QtCore.QRect(255, 322, 200, 30))
        self.entry_btn_entry_page.setStyleSheet("background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;\n"
"color: #FFFFFF;\n"
"")
        self.entry_btn_entry_page.setObjectName("entry_btn_entry_page")
        self.entry_login_edit = QtWidgets.QLineEdit(self.entry_page)
        self.entry_login_edit.setGeometry(QtCore.QRect(255, 222, 200, 30))
        self.entry_login_edit.setMinimumSize(QtCore.QSize(200, 30))
        self.entry_login_edit.setMaximumSize(QtCore.QSize(200, 30))
        self.entry_login_edit.setStyleSheet("border: 1px solid #006F48;\n"
"border-radius: 10px;")
        self.entry_login_edit.setText("")
        self.entry_login_edit.setObjectName("entry_login_edit")
        self.entry_pass_edit = QtWidgets.QLineEdit(self.entry_page)
        self.entry_pass_edit.setGeometry(QtCore.QRect(255, 272, 200, 30))
        self.entry_pass_edit.setMinimumSize(QtCore.QSize(200, 30))
        self.entry_pass_edit.setMaximumSize(QtCore.QSize(200, 30))
        self.entry_pass_edit.setStyleSheet("border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"")
        self.entry_pass_edit.setObjectName("entry_pass_edit")
        self.label = QtWidgets.QLabel(self.entry_page)
        self.label.setGeometry(QtCore.QRect(318, 147, 65, 35))
        self.label.setMinimumSize(QtCore.QSize(65, 35))
        self.label.setMaximumSize(QtCore.QSize(65, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 145%;")
        self.label.setObjectName("label")
        self.back_btn_entry = QtWidgets.QPushButton(self.entry_page)
        self.back_btn_entry.setGeometry(QtCore.QRect(20, 20, 25, 25))
        self.back_btn_entry.setMinimumSize(QtCore.QSize(25, 25))
        self.back_btn_entry.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_btn_entry.setFont(font)
        self.back_btn_entry.setStyleSheet("border-radius: 10px;\n"
"\n"
"")
        self.back_btn_entry.setText("")
        self.back_btn_entry.setIcon(icon)
        self.back_btn_entry.setIconSize(QtCore.QSize(25, 25))
        self.back_btn_entry.setObjectName("back_btn_entry")
        self.stackedWidget.addWidget(self.entry_page)
        self.menu_page = QtWidgets.QWidget()
        self.menu_page.setObjectName("menu_page")
        self.clients_btn = QtWidgets.QPushButton(self.menu_page)
        self.clients_btn.setGeometry(QtCore.QRect(250, 160, 200, 30))
        self.clients_btn.setStyleSheet("background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;")
        self.clients_btn.setObjectName("clients_btn")
        self.proc_btn = QtWidgets.QPushButton(self.menu_page)
        self.proc_btn.setGeometry(QtCore.QRect(250, 210, 200, 30))
        self.proc_btn.setStyleSheet("background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;")
        self.proc_btn.setObjectName("proc_btn")
        self.rooms_btn = QtWidgets.QPushButton(self.menu_page)
        self.rooms_btn.setGeometry(QtCore.QRect(250, 260, 200, 30))
        self.rooms_btn.setStyleSheet("background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;")
        self.rooms_btn.setObjectName("rooms_btn")
        self.exit_btn = QtWidgets.QPushButton(self.menu_page)
        self.exit_btn.setGeometry(QtCore.QRect(250, 310, 200, 30))
        self.exit_btn.setStyleSheet("background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;")
        self.exit_btn.setObjectName("exit_btn")
        self.employees_btn = QtWidgets.QPushButton(self.menu_page)
        self.employees_btn.setGeometry(QtCore.QRect(250, 110, 200, 30))
        self.employees_btn.setStyleSheet("background: #006F48;\n"
"border: 1px solid #006F48;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 11px;\n"
"line-height: 145%;")
        self.employees_btn.setObjectName("employees_btn")
        self.stackedWidget.addWidget(self.menu_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.entry_btn.setText(_translate("MainWindow", "Войти"))
        self.regisration_btn.setText(_translate("MainWindow", "Регистрация"))
        self.label_9.setText(_translate("MainWindow", "Программное средство санатория"))
        item = self.table_of_rooms.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.table_of_rooms.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.table_of_rooms.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.table_of_rooms.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Комната"))
        item = self.table_of_rooms.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Паспорт"))
        item = self.table_of_rooms.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Номер телефона"))
        self.back_btn_rooms.setText(_translate("MainWindow", "Назад"))
        self.label_16.setText(_translate("MainWindow", "Комнаты"))
        self.search_btn_rooms.setText(_translate("MainWindow", "Поиск"))
        self.delete_btn_rooms.setText(_translate("MainWindow", "Удалить"))
        self.edit_btn_rooms.setText(_translate("MainWindow", "Редактировать"))
        self.sorting_btn_rooms.setText(_translate("MainWindow", "Сортировка"))
        item = self.table_of_proc.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.table_of_proc.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.table_of_proc.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.table_of_proc.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Комната"))
        item = self.table_of_proc.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Паспорт"))
        item = self.table_of_proc.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Номер телефона"))
        self.back_btn_proc.setText(_translate("MainWindow", "Назад"))
        self.label_15.setText(_translate("MainWindow", "Процедуры"))
        self.search_btn_proc.setText(_translate("MainWindow", "Поиск"))
        self.delete_btn_proc.setText(_translate("MainWindow", "Удалить"))
        self.edit_btn_proc.setText(_translate("MainWindow", "Редактировать"))
        self.sorting_btn_proc.setText(_translate("MainWindow", "Сортировка"))
        item = self.table_of_clients.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.table_of_clients.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.table_of_clients.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.table_of_clients.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Комната"))
        item = self.table_of_clients.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Паспорт"))
        item = self.table_of_clients.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Номер телефона"))
        self.label_14.setText(_translate("MainWindow", "Клиенты"))
        self.back_btn_clients.setText(_translate("MainWindow", "Назад"))
        self.search_btn_clients.setText(_translate("MainWindow", "Поиск"))
        self.delete_btn_clients.setText(_translate("MainWindow", "Удалить"))
        self.edit_btn_clients.setText(_translate("MainWindow", "Редактировать"))
        self.sorting_btn_clients.setText(_translate("MainWindow", "Сортировка"))
        item = self.table_of_emlp.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.table_of_emlp.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.table_of_emlp.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.table_of_emlp.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Должность"))
        item = self.table_of_emlp.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Зарплата"))
        item = self.table_of_emlp.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "График"))
        item = self.table_of_emlp.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Телефон"))
        item = self.table_of_emlp.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Адрес"))
        self.back_btn_empl.setText(_translate("MainWindow", "Назад"))
        self.sorting_btn_empl.setText(_translate("MainWindow", "Сортировка"))
        self.delete_btn_empl.setText(_translate("MainWindow", "Удалить"))
        self.edit_btn_empl.setText(_translate("MainWindow", "Редактировать"))
        self.label_8.setText(_translate("MainWindow", "Сотрудники"))
        self.search_btn_empl.setText(_translate("MainWindow", "Поиск"))
        self.label_4.setText(_translate("MainWindow", "Регистрация"))
        self.reg_btn_reg_page.setText(_translate("MainWindow", "Зарегестрироваться"))
        self.entry_btn_entry_page.setText(_translate("MainWindow", "Войти"))
        self.label.setText(_translate("MainWindow", "Вход"))
        self.clients_btn.setText(_translate("MainWindow", "Клиенты"))
        self.proc_btn.setText(_translate("MainWindow", "Процедуры"))
        self.rooms_btn.setText(_translate("MainWindow", "Комнаты"))
        self.exit_btn.setText(_translate("MainWindow", "Во вход"))
        self.employees_btn.setText(_translate("MainWindow", "Сотрудники"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
